# Just a temp makefile, will have to update it to be more streamlined
# in the future

all: prob1 prob2 prob3

prob1:
	gcc -g -Wall prob1.c -o one

prob2:
	gcc -g -Wall prob2.c -o two

prob3:
	gcc -g -Wall prob3.c -o three

clean:
	rm one two three
